### ISSUE TITLE
Error: Promised response from onMessage listener went out of scope

### ISSUE THREAD

**Issue by short-circuit** [tianve/sketchfab_download_userscipt#11]
When the download button is pressed, the webdev console spits out the following error:
`Error: Promised response from onMessage listener went out of scope`
and no download is being executed. Script worked perfectly and then all of a sudden not anymore at all. No matter if I try to download already downloaded models. Maybe some kind of softban? Any way around it?

**Comment by paomian4** [comment]
There is no response to pressing the download button

**Comment by short-circuit** [comment]
> 
> 
> There is no response to pressing the download button

Can you please specify what you mean? As in it should not have a response or it is not responding and so not working?

I always had a logged command in the webdev console when I press the download button, so not sure if anything wrong there. To me it seems that it is not working at all anymore.

**Comment by LotharieSlayer** [comment]
> When the download button is pressed, the webdev console spits out the following error:
> `Error: Promised response from onMessage listener went out of scope`
> and no download is being executed. Script worked perfectly and then all of a sudden not anymore at all. No matter if I try to download already downloaded models. Maybe some kind of softban? Any way around it?

I've the same error.

**Comment by phrankinstein** [comment]
Likewise having this issue first time trying to use.

**Comment by maksla** [comment]
To the author of the script. If there is a problem with the button, maybe make an automatic download? After all, the script is easy to disable or enable in the browser.

**Comment by tianve** [comment]
fixed@2021/07/28

**Comment by setsunakawa** [comment]
updated and still not working, same error.
