### ISSUE TITLE
do not work any more

### ISSUE THREAD

**Issue by lipeiji** [tianve/sketchfab_download_userscipt#13]

**Comment by tianve** [comment]
fixed@2021/07/28

**Comment by lipeiji** [comment]
You're really a genius！&nbsp;Thank you for your kind reply！&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tianve/sketchfab_download_userscipt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 下午3:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tianve/sketchfab_download_userscipt] do not work any more (#13)





 
Closed #13.
