### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by Khuengoan** [tianve/sketchfab_download_userscipt#14]
I succesfully downloaded the model as .obj format but I can't open or use them. Plus I don't know what to do with the viewer.txt file, I can't seem to be able to import it to tampermonkey. Am I supposed to export it to a different format ? Sorry I'm very bad at coding stuff : (

**Comment by miccall** [comment]
@Khuengoan don't need viewer.txt file . if you want open .obj format file . you need software like autodesk maya 。

**Comment by tianve** [comment]
> @Khuengoan don't need viewer.txt file . if you want open .obj format file . you need software like autodesk maya 。

**Comment by Khuengoan** [comment]
ah I figured out that the model I downloaded has a bunch of decoy files that display jacked up geometry or unable to open. Thanks for helping out.
