### ISSUE TITLE
Does Not Work 7/28/21

### ISSUE THREAD

**Issue by danish1234567danish** [tianve/sketchfab_download_userscipt#15]
Updated to most recent version, still does not function.

**Comment by LotharieSlayer** [comment]
same here `Error: Promised response from onMessage listener went out of scope` after the `download` log

**Comment by miccall** [comment]
```

else if (jstext.indexOf("drawImplementation:function(t){var r=v") >= 0) {
                console.log("inject6:" + src);
                jstext = jstext.split("drawImplementation:function(t){var r=v").join("drawImplementation:function(t){window.drawhook(this);var r=v");
            }
```

**Comment by Jetical** [comment]
epic games now owns Sketchfab, that extra code might be whats causing issues (whatever they added to the code), its either that or this person again, i remeber a while back they were a problem, "https://sketchfab-ripper.com/"

**Comment by tianve** [comment]
use RegExp for Injection, hope it works longer

**Comment by XEODIX** [comment]
>  RegExp

How or what is RegExp?
Okay i understand it, but i have no idea how to run it?
