### ISSUE TITLE
Used to work until a few days ago.

### ISSUE THREAD

**Issue by X3Zero** [tianve/sketchfab_download_userscipt#6]
This used to work until a few days ago, I even downgraded to see if it'll help, still nothing.

**Comment by amrnablus** [comment]
@tianye910208 i'd like to help fixing that but i'm not that familiar with the code, anything i can do to help?

**Comment by raouf45** [comment]
@tianye910208 you will make alot of people happy if you fix it 
waiting for update
thank you

**Comment by alexiscn** [comment]
I have fixed this script by changing "web/dist/viewer" to "web/dist/standaloneViewer" at line 242

**Comment by X3Zero** [comment]
> I have fixed this script by changing "web/dist/viewer" to "web/dist/standaloneViewer" at line 242

Awsome, this worked! Thank you.
