### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by TokarTheGreatest** [tianve/sketchfab_download_userscipt#7]
script does not work

**Comment by JPEGjackal** [comment]
can confirm, stopped working yesterday

**Comment by gustavorrezende** [comment]
Doesn't work anymore.

**Comment by hujiba** [comment]
aw did it seriously stop working a week before I needed to use it?

**Comment by XEODIX** [comment]
outdated now, hit me up on DM on how i can help,

**Comment by cjcjcj89** [comment]
+ 

Me too. there is a download button but nothing happens.
I thought it was about updating tampermonkey, but it still does not work with its old versions.

**Comment by tianve** [comment]
Fixed @2021/03/29
