### ISSUE TITLE
The script stopped working today 

### ISSUE THREAD

**Issue by maksla** [tianve/sketchfab_download_userscipt#8]
Сlicking on "download" doesn't do anything.
And if there is a patch, maybe you can download the animation?

**Comment by miccall** [comment]
its moved to : https://static.sketchfab.com/static/builds/web/dist/kekw-v2-0a905e189a891731b67733d595895f3d.js . 
“drawImplementation” Seems to be confused by the code 。

**Comment by im-nassinger** [comment]
please update the code 😔

**Comment by tianve** [comment]
fixed.
